version: '3'
services:
  node:
    build:
      context: ..
      dockerfile: ./.docker/images/node/Dockerfile
    tty: true
    volumes:
      - ..:/var/www
      - node_modules:/var/www/node_modules
    env_file:
      - .env.dev
    ports:
      - 3000:3000
      - 5555:5555

volumes:
  node_modules:
    driver: local
